# Generated by Django 5.0.1 on 2024-02-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_address_contact_delete_bug_delete_vulnerability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='kifle_ketema',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='address',
            name='woreda',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
