# Generated by Django 5.0.1 on 2024-02-29 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_state_address_kifle_ketema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.contact'),
        ),
        migrations.AlterField(
            model_name='address',
            name='kifle_ketema',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
