# Generated by Django 5.0.1 on 2024-02-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_address_contact_alter_address_kifle_ketema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='kifle_ketema',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='woreda',
        ),
        migrations.AddField(
            model_name='address',
            name='address_line1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
